name: Scala CI

on:
  pull_request:
  push:
    branches:
      - master
      - 're-releases-*'
      - '*-pushbuild'

env:
  JAVA_OPTS: -Xms6g -Xmx6g -XX:+UseG1GC
  JDK_JAVA_OPTIONS: -Xms6g -Xmx6g -XX:+UseG1GC # See https://stackoverflow.com/a/73708006

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [3.3.0]
        module: [sqltest, db, async, bigdata]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: actions/setup-java@v3.12.0
      with:
        distribution: temurin
        java-version: '8'
        check-latest: true

    - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
      env:
        SCALA_VERSION: ${{ matrix.scala }}
      run: |
        echo "SCALA_VERSION='$SCALA_VERSION'"
        ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        scala: [3.3.0]
        module: [base, db, async, bigdata, publish]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: actions/setup-java@v3.12.0
      with:
        distribution: temurin
        java-version: '8'
        check-latest: true
    - run: |
        echo "PULL_REQUEST='$PULL_REQUEST'"
        export BRANCH=$(git for-each-ref ${{ github.ref }} --format='%(refname:short)')
        echo "BRANCH='$BRANCH'"
        ./build/release.sh ${{ matrix.module }}
      env:
        ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PULL_REQUEST: ${{ !!github.event.pull_request }}