name: Scala CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [ published ] # Triggers the CI when a new GitHub Release is published

env:
  # See:
  #  - https://stackoverflow.com/a/73708006
  #  - https://stackoverflow.com/questions/73465937/apache-spark-3-3-0-breaks-on-java-17-with-cannot-access-class-sun-nio-ch-direct
  JDK_JAVA_OPTIONS: -Xms6g -Xmx6g -XX:+UseG1GC --add-exports java.base/sun.nio.ch=ALL-UNNAMED

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        scala: [ 3.3.1 ]
        module: [ sqltest, db, async, bigdata ]

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Java and Scala
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: '17'
          check-latest: true

      - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
        env:
          SCALA_VERSION: ${{ matrix.scala }}
        run: |
          echo "SCALA_VERSION='$SCALA_VERSION'"
          ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Setup Java and Scala
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: '17'
          check-latest: true
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
