name: Scala CI

on:
  push:
    branches:
      - "**"
    # tags:
    #   - "**"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [3.0.0]
        module: [sqltest, db, async, bigdata]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0

    - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 180
        max_attempts: 3
        command: |
          export TRAVIS_SCALA_VERSION=${{ matrix.scala }}
          echo "TRAVIS_SCALA_VERSION='$TRAVIS_SCALA_VERSION'"
          ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        scala: [3.0.0]
        module: [base, db, async, bigdata, publish]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0
    - run: |
        export ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}
        export PGP_PASSPHRASE=${{ secrets.PGP_PASSPHRASE }}
        export TRAVIS_PULL_REQUEST=${{ !!github.event.pull_request }}
        echo "TRAVIS_PULL_REQUEST='$TRAVIS_PULL_REQUEST'"
        export TRAVIS_BRANCH=$(git for-each-ref ${{ github.ref }} --format='%(refname:short)')
        echo "TRAVIS_BRANCH='$TRAVIS_BRANCH'"
        ./build/release.sh ${{ matrix.module }}
