name: Scala CI

on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [ published ] # Triggers the CI when a new GitHub Release is published

env:
  JAVA_OPTS: -Xms6g -Xmx6g -XX:+UseG1GC
  JDK_JAVA_OPTIONS: -Xms6g -Xmx6g -XX:+UseG1GC # See https://stackoverflow.com/a/73708006

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [ 3.3.1 ]
        module: [ sqltest, db, async, bigdata ]

    steps:
      - uses: actions/checkout@v4.0.0
      - name: Setup Java and Scala
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: '8'
          check-latest: true

      - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
        env:
          SCALA_VERSION: ${{ matrix.scala }}
        run: |
          echo "SCALA_VERSION='$SCALA_VERSION'"
          ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Setup Java and Scala
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: '8'
          check-latest: true
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
