name: Scala CI

on:
  push:
    branches:
      - "**"
    # tags:
    #   - "**"

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala: [3.3.0]
        module: [sqltest, db, async, bigdata]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0

    - name: Scala ${{ matrix.scala }} Building ${{ matrix.module }}
      run: |
        export SCALA_VERSION=${{ matrix.scala }}
        echo "SCALA_VERSION='$SCALA_VERSION'"
        ./build/build.sh ${{ matrix.module }}

  release:
    if: ${{github.event_name != 'pull_request'}}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        scala: [3.3.0]
        module: [base, db, async, bigdata, publish]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java and Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: 1.8.0
    - run: |
        export ENCRYPTION_PASSWORD=${{ secrets.ENCRYPTION_PASSWORD }}
        export PGP_PASSPHRASE=${{ secrets.PGP_PASSPHRASE }}
        export PULL_REQUEST=${{ !!github.event.pull_request }}
        echo "PULL_REQUEST='$PULL_REQUEST'"
        export BRANCH=$(git for-each-ref ${{ github.ref }} --format='%(refname:short)')
        echo "BRANCH='$BRANCH'"
        ./build/release.sh ${{ matrix.module }}
